version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
    container_name: 'mfg-bk-api'
    restart: 'on-failure' #always
    depends_on:
      - db
    expose:
      - '4000'
    ports:
      - '4000:4000'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - bk_api_backend
  db:
    image: mysql:5.7
    #ports:
    #  - "3306:3306"
    container_name: 'mfg-bk-db'
    restart: always
    environment:
      MYSQL_DATABASE: 'bkapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'minor@1234'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      #- /Users/Macbook/stack/stack1_sz/db/data:/var/lib/mysql
      - /home/minor/stack/volume/bk-api/db/data:/var/lib/mysql
    networks:
      - bk_api_backend
  admin:
    image: adminer
    ports:
      - '8090:8080'
    container_name: 'mfg-bk-db-admin'
    restart: always
    networks:
      - bk_api_backend
# Networks to be created to facilitate communication between containers
networks:
  bk_api_backend:

#services:
#  mfg-4b-sz:
    #build:
    #  context: .
    #  labels:
    #    - "com.minor.description=Sizzler webapp"
    #    - "com.minor.department=FoodIT"
    #  target: prod
    #deploy:
    #  mode: replicated = * / global=1
    #  replicas: 1
    #  endpoint_mode: dnsrr
    #  labels:
    #        com.example.description: "This label will appear on the web service"
    #  placement:
    #    constraints:
    #      - node.role == manager
    #      - engine.labels.operatingsystem == ubuntu 14.04
    #    preferences:
    #      - spread: node.labels.zone
    #  resources:
    #    limits:
    #      cpus: '0.50'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 20M
    #  restart_policy: #Out of memory exception
    #    condition: on-failure
    #    delay: 5s
    #    max_attempts: 3
    #    window: 120s
    #logging:
    #  driver: "json-file"
    #  options:
    #    max-size: "200k"
    #    max-file: "10"
    #network_mode: "bridge"
    #networks:
    #  - some-network
    #  - other-network
    #port:port #HOST:CONTAINER
#devices:
#  - "/dev/ttyUSB0:/dev/ttyUSB0"
#dns: 8.8.8.8
#entrypoint:
#  - /code/entrypoint.sh
#env_file:
#  - ./common.env
#  - ./apps/web.env
#environment:
#  - RACK_ENV=development
#  - SHOW=true
#  - SESSION_SECRET
#extra_hosts:
#  - "somehost:162.242.195.82"
#  - "otherhost:50.31.209.229"
#healthcheck:
#  test: ["CMD", "curl", "-f", "http://localhost"]
#  interval: 1m30s
#  timeout: 10s
#  retries: 3
#  start_period: 40s
