const configEnv = require('dotenv').config()
var soap = require('soap');
var url = process.env.SDK_URL;

module.exports = function(args,cb) {
  soap.createClient(url ,{
    rejectUnauthorized: false,
    strictSSL: false
  }, function(err, client) {
      if(err){
        console.log(err);
      }else{
        client.GetDistrictsList(args, function(err1, result) {      
          if(!result.GetDistrictsListResult){
            cb(err1,result.SDKResult);
          }else{
            cb(err1,result.GetDistrictsListResult);
          }
        });  
      }
      
  });
}

/**
var get_comp_args = {
    licenseCode: process.env.LICENSECODE,
    requestID: '201909171328',
    language: 'En',
    countryID: ''
    provinceID: ''
    cityID: ''
    text: ''
    searchType: ''  //0 means ‘Contains’, 1 means ‘Exact’
}
 */

 /*
{ CC_CITY:
   [ { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1015',
       CTY_NAME: 'ประจวบคีรีขันธ์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1013',
       CTY_NAME: 'กำแพงเพชร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1069',
       CTY_NAME: 'สตูล',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1011',
       CTY_NAME: 'สมุทรสงคราม',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1018',
       CTY_NAME: 'กาฬสินธุ์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1058',
       CTY_NAME: 'ตาก',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1006',
       CTY_NAME: 'พระนครศรีอยุธยา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1007',
       CTY_NAME: 'สระบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '-1',
       CTY_CODE: '',
       CTY_ID: '-1',
       CTY_NAME: 'Unspecified',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '-1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1',
       CTY_NAME: 'กรุงเทพมหานคร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1000',
       CTY_NAME: 'นครปฐม',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1001',
       CTY_NAME: 'นนทบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1002',
       CTY_NAME: 'ปทุมธานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1003',
       CTY_NAME: 'สมุทรปราการ',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1004',
       CTY_NAME: 'สมุทรสาคร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1075',
       CTY_NAME: 'อ่างทอง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1076',
       CTY_NAME: 'สระแก้ว',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1077',
       CTY_NAME: 'ยโสธร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1078',
       CTY_NAME: 'อำนาจเจริญ',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1079',
       CTY_NAME: 'บึงกาฬ',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1080',
       CTY_NAME: 'น่าน',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1081',
       CTY_NAME: 'แม่ฮ่องสอน',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1082',
       CTY_NAME: 'อุทัยธานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1083',
       CTY_NAME: 'นราธิวาส',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1068',
       CTY_NAME: 'พังงา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1019',
       CTY_NAME: 'ฉะเชิงเทรา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1020',
       CTY_NAME: 'จันทบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1021',
       CTY_NAME: 'เชียงใหม่',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1022',
       CTY_NAME: 'เชียงราย',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1023',
       CTY_NAME: 'ชลบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1024',
       CTY_NAME: 'ชุมพร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1025',
       CTY_NAME: 'กาญจนบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1001' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1026',
       CTY_NAME: 'ขอนแก่น',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1027',
       CTY_NAME: 'กระบี่',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1028',
       CTY_NAME: 'ลำปาง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1029',
       CTY_NAME: 'ลพบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1030',
       CTY_NAME: 'ลำพูน',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1031',
       CTY_NAME: 'มหาสารคาม',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1032',
       CTY_NAME: 'มุกดาหาร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1033',
       CTY_NAME: 'นครสวรรค์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1034',
       CTY_NAME: 'นครศรีธรรมราช',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1035',
       CTY_NAME: 'นครราชสีมา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1036',
       CTY_NAME: 'หนองคาย',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1037',
       CTY_NAME: 'เพชรบูรณ์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1038',
       CTY_NAME: 'เพชรบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1001' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1039',
       CTY_NAME: 'พิษณุโลก',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1040',
       CTY_NAME: 'แพร่',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1041',
       CTY_NAME: 'ภูเก็ต',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1042',
       CTY_NAME: 'ปราจีนบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1043',
       CTY_NAME: 'ราชบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1001' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1044',
       CTY_NAME: 'ระยอง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1045',
       CTY_NAME: 'ร้อยเอ็ด',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1046',
       CTY_NAME: 'สกลนคร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1047',
       CTY_NAME: 'สิงห์บุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1048',
       CTY_NAME: 'ศรีสะเกษ',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1049',
       CTY_NAME: 'สงขลา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1050',
       CTY_NAME: 'สุพรรณบุรี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1051',
       CTY_NAME: 'สุราษฎร์ธานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1052',
       CTY_NAME: 'สุรินทร์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1053',
       CTY_NAME: 'ตรัง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1054',
       CTY_NAME: 'อุดรธานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1055',
       CTY_NAME: 'อุตรดิตถ์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1056',
       CTY_NAME: 'อุบลราชธานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1071',
       CTY_NAME: 'ชัยนาท',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1074',
       CTY_NAME: 'พะเยา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1002' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1072',
       CTY_NAME: 'นครพนม',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1010',
       CTY_NAME: 'บุรีรัมย์',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1059',
       CTY_NAME: 'พัทลุง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1060',
       CTY_NAME: 'ยะลา',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1012',
       CTY_NAME: 'เลย',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1070',
       CTY_NAME: 'หนองบัวลำภู',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1064',
       CTY_NAME: 'ชัยภูมิ',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1004' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1062',
       CTY_NAME: 'ปัตตานี',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1063',
       CTY_NAME: 'สุโขทัย',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1065',
       CTY_NAME: 'พิจิตร',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1066',
       CTY_NAME: 'ตราด',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1003' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1067',
       CTY_NAME: 'ระนอง',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1005' },
     { CTY_CNTID: '1',
       CTY_CODE: '',
       CTY_ID: '1073',
       CTY_NAME: 'นครนายก',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1' },
     { CTY_CNTID: '4',
       CTY_CODE: '',
       CTY_ID: '1085',
       CTY_NAME: 'Male-Maldives',
       CTY_NAMEUN: '',
       CTY_PROVINCEID: '1007' } ] }
*/