const configEnv = require('dotenv').config()
var soap = require('soap');
var url = process.env.SDK_URL;

module.exports = function(args,cb) {
  soap.createClient(url ,{
    rejectUnauthorized: false,
    strictSSL: false
  }, function(err, client) {
      if(err){
        console.log(err);
      }
      client.GetWebCountriesList(args, function(err1, result) {
            //console.log('GetWebCountriesList');
            
            if(!result.GetWebCountriesListResult){
              cb(err1,result.SDKResult);
            }else{
              cb(err1,result.GetWebCountriesListResult);
            }
      });  
  });
}

/**
var get_comp_args = {
    licenseCode: process.env.LICENSECODE,
    requestID: '201909171328',
    language: 'En'
}
 */

 /*
{ CC_WEB_CITY:
   [ { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1',
       CTY_NAME: 'Bangkok',
       CTY_NAMEUN: 'กรุงเทพมหานคร',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1000',
       CTY_NAME: 'Nakhonpathom',
       CTY_NAMEUN: 'นครปฐม',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1001',
       CTY_NAME: 'Nonthaburi',
       CTY_NAMEUN: 'นนทบุรี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1002',
       CTY_NAME: 'Pathumthani',
       CTY_NAMEUN: 'ปทุมธานี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1003',
       CTY_NAME: 'Samutprakan',
       CTY_NAMEUN: 'สมุทรปราการ',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1004',
       CTY_NAME: 'Samutsakhon',
       CTY_NAMEUN: 'สมุทรสาคร',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1006',
       CTY_NAME: 'Ayutthaya',
       CTY_NAMEUN: 'พระนครศรีอยุธยา',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1007',
       CTY_NAME: 'Saraburi',
       CTY_NAMEUN: 'สระบุรี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1010',
       CTY_NAME: 'Buriram',
       CTY_NAMEUN: 'บุรีรัมย์',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1011',
       CTY_NAME: 'Samutsongkhram',
       CTY_NAMEUN: 'สมุทรสงคราม',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1012',
       CTY_NAME: 'Loei',
       CTY_NAMEUN: 'เลย',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1013',
       CTY_NAME: 'Kamphaengphet',
       CTY_NAMEUN: 'กำแพงเพชร',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1015',
       CTY_NAME: 'Prachuapkhirikhan',
       CTY_NAMEUN: 'ประจวบคีรีขันธ์',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1018',
       CTY_NAME: 'Kalasin',
       CTY_NAMEUN: 'กาฬสินธุ์',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1019',
       CTY_NAME: 'Chachoengsao',
       CTY_NAMEUN: 'ฉะเชิงเทรา',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1020',
       CTY_NAME: 'Chanthaburi',
       CTY_NAMEUN: 'จันทบุรี',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1021',
       CTY_NAME: 'Chiangmai',
       CTY_NAMEUN: 'เชียงใหม่',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1022',
       CTY_NAME: 'Chiangrai',
       CTY_NAMEUN: 'เชียงราย',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1023',
       CTY_NAME: 'Chonburi',
       CTY_NAMEUN: 'ชลบุรี',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1024',
       CTY_NAME: 'Chumphon',
       CTY_NAMEUN: 'ชุมพร',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1025',
       CTY_NAME: 'Kanchanaburi',
       CTY_NAMEUN: 'กาญจนบุรี',
       CTY_PROVINCEID: '1001' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1026',
       CTY_NAME: 'Khonkaen',
       CTY_NAMEUN: 'ขอนแก่น',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1027',
       CTY_NAME: 'Krabi',
       CTY_NAMEUN: 'กระบี่',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1028',
       CTY_NAME: 'Lampang',
       CTY_NAMEUN: 'ลำปาง',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1029',
       CTY_NAME: 'Lopburi',
       CTY_NAMEUN: 'ลพบุรี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1030',
       CTY_NAME: 'Lumphun',
       CTY_NAMEUN: 'ลำพูน',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1031',
       CTY_NAME: 'Mahasarakham',
       CTY_NAMEUN: 'มหาสารคาม',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1032',
       CTY_NAME: 'Mukdahan',
       CTY_NAMEUN: 'มุกดาหาร',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1033',
       CTY_NAME: 'Nakhonsawan',
       CTY_NAMEUN: 'นครสวรรค์',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1034',
       CTY_NAME: 'Nakhonsithammarat',
       CTY_NAMEUN: 'นครศรีธรรมราช',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1035',
       CTY_NAME: 'Nakonratchasima',
       CTY_NAMEUN: 'นครราชสีมา',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1036',
       CTY_NAME: 'Nongkhai',
       CTY_NAMEUN: 'หนองคาย',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1037',
       CTY_NAME: 'Phetchabun',
       CTY_NAMEUN: 'เพชรบูรณ์',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1038',
       CTY_NAME: 'Phetchaburi',
       CTY_NAMEUN: 'เพชรบุรี',
       CTY_PROVINCEID: '1001' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1039',
       CTY_NAME: 'Phitsnulok',
       CTY_NAMEUN: 'พิษณุโลก',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1040',
       CTY_NAME: 'Phrae',
       CTY_NAMEUN: 'แพร่',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1041',
       CTY_NAME: 'Phuket',
       CTY_NAMEUN: 'ภูเก็ต',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1042',
       CTY_NAME: 'Prachinburi',
       CTY_NAMEUN: 'ปราจีนบุรี',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1043',
       CTY_NAME: 'Ratchaburi',
       CTY_NAMEUN: 'ราชบุรี',
       CTY_PROVINCEID: '1001' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1044',
       CTY_NAME: 'Rayong',
       CTY_NAMEUN: 'ระยอง',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1045',
       CTY_NAME: 'Roiet',
       CTY_NAMEUN: 'ร้อยเอ็ด',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1046',
       CTY_NAME: 'Sakonnakhon',
       CTY_NAMEUN: 'สกลนคร',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1047',
       CTY_NAME: 'Singburi',
       CTY_NAMEUN: 'สิงห์บุรี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1048',
       CTY_NAME: 'Srisaket',
       CTY_NAMEUN: 'ศรีสะเกษ',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1049',
       CTY_NAME: 'Songkhla',
       CTY_NAMEUN: 'สงขลา',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1050',
       CTY_NAME: 'Suphanburi',
       CTY_NAMEUN: 'สุพรรณบุรี',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1051',
       CTY_NAME: 'Suratthani',
       CTY_NAMEUN: 'สุราษฎร์ธานี',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1052',
       CTY_NAME: 'Surin',
       CTY_NAMEUN: 'สุรินทร์',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1053',
       CTY_NAME: 'Trang',
       CTY_NAMEUN: 'ตรัง',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1054',
       CTY_NAME: 'Udonthani',
       CTY_NAMEUN: 'อุดรธานี',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1055',
       CTY_NAME: 'Uttaradit',
       CTY_NAMEUN: 'อุตรดิตถ์',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1056',
       CTY_NAME: 'Ubonratchathani',
       CTY_NAMEUN: 'อุบลราชธานี',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1058',
       CTY_NAME: 'Tak',
       CTY_NAMEUN: 'ตาก',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1059',
       CTY_NAME: 'Phatthalung',
       CTY_NAMEUN: 'พัทลุง',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1060',
       CTY_NAME: 'Yala',
       CTY_NAMEUN: 'ยะลา',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1062',
       CTY_NAME: 'Pattani',
       CTY_NAMEUN: 'ปัตตานี',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1063',
       CTY_NAME: 'Sukhothai',
       CTY_NAMEUN: 'สโขทัย',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1064',
       CTY_NAME: 'Chaiyaphum',
       CTY_NAMEUN: 'ชัยภูมิ',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1065',
       CTY_NAME: 'Phichit',
       CTY_NAMEUN: 'พิจิตร',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1066',
       CTY_NAME: 'Trad',
       CTY_NAMEUN: 'ตราด',
       CTY_PROVINCEID: '1003' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1067',
       CTY_NAME: 'Ranong',
       CTY_NAMEUN: 'ระนอง',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1068',
       CTY_NAME: 'Phangnga',
       CTY_NAMEUN: 'พังงา',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1069',
       CTY_NAME: 'Satun',
       CTY_NAMEUN: 'สตูล',
       CTY_PROVINCEID: '1005' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1070',
       CTY_NAME: 'Nongbualumpu',
       CTY_NAMEUN: 'หนองบัวลำภู',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1071',
       CTY_NAME: 'Chainat',
       CTY_NAMEUN: 'ชัยนาท',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1072',
       CTY_NAME: 'Nakhonpanom',
       CTY_NAMEUN: 'นครพนม',
       CTY_PROVINCEID: '1004' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1073',
       CTY_NAME: 'Nakhonnayok',
       CTY_NAMEUN: 'นครนายก',
       CTY_PROVINCEID: '1' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1074',
       CTY_NAME: 'Phayao',
       CTY_NAMEUN: 'พะเยา',
       CTY_PROVINCEID: '1002' },
     { CTY_ACTIVE: 1,
       CTY_CNTID: '1',
       CTY_ID: '1080',
       CTY_NAME: 'Nan',
       CTY_NAMEUN: 'น่าน',
       CTY_PROVINCEID: '1002' } ] }
*/