CREATE TABLE bkapi.sites (
	ID int(10) NOT NULL auto_increment,
	sitegroup varchar(25) NOT NULL,
	siteID varchar(25) NOT NULL,
	siteNumber varchar(25) NOT NULL,
	siteName varchar(400) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bkapi.orders (
	id bigint(19) NOT NULL auto_increment,
    channel varchar(100),
	addressID varchar(100),
	areaID varchar(100),
	storeID varchar(40),
	storeName varchar(255),
	storeNumber varchar(40),
	orderMode int(10),
	orderName varchar(255),
	orderType int(10),
	tranDate timestamp NULL DEFAULT NULL,
	dueDate timestamp NULL DEFAULT NULL,
	customerID varchar(100),
	grossTotal decimal(15,2),
	discountTotal decimal(15,2),
	refID varchar(100),
	transactionBy varchar(255),
	createdDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	json longtext,
	site varchar(40),
	status varchar(10),
	entries longtext,
	cookingFinishTime timestamp NULL DEFAULT NULL,
	pickupFinishTime timestamp NULL DEFAULT NULL ,
	cancelTime timestamp NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bkapi.customers (
	ID bigint(19) NOT NULL auto_increment,
	customerID varchar(40),
	corpID varchar(40),
    webcustomerID varchar(40),
	sdmEmailMap varchar(255),
	email varchar(255),
	username varchar(255),  
	password varchar(100),
	firstname varchar(255),
	lastname varchar(255),
	gender varchar(255),
	dateOfBirth timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	martialStatus varchar(40),
	nationalityID varchar(40),
	preferedLang varchar(40),
	phoneType varchar(40),
	phoneLookup varchar(40),
	phoneNumber varchar(40),
	status varchar(40),
	offer1 bit(1),
	offer2 bit(1),
	channel varchar(40),
	phatform varchar(40),
    active bit(1),
    createdDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sitegroup varchar(25) NOT NULL,
	token varchar(1024),
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bkapi.address (
	ID bigint(19) NOT NULL auto_increment,
	addressID varchar(40),
	webaddressID varchar(40),
	customerID varchar(40),
	storeID varchar(10),
	addressName varchar(100),
	provinceID varchar(20),
	cityID varchar(20),
	distinctID varchar(20),
	streetID varchar(20),
	areaID varchar(20),
	roomNo varchar(20),
	buildNo varchar(20),
	buildName varchar(200),
	floor varchar(20),
	street varchar(200),
	district varchar(300),
	subdistrict varchar(200),
	postCode varchar(50),
	areaText varchar(200),
	direction varchar(800),
	lat varchar(20),
	lng varchar(20),
	status varchar(20),
    isDefault varchar(10),
	active binary(1),
	channel varchar(40),
	phatform varchar(40),
    createdDate timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bkapi.cc_itm (
	ID bigint(19) NOT NULL auto_increment,
	MENU_ID varchar(40),
	ITEM_ID varchar(40),
	USERNUMBER varchar(40),
	SHORTNAME varchar(400),
	LONGNAME varchar(400),
	TAXID varchar(5),
	PRINTONCHK varchar(5),
	COMBINE varchar(5),
	MOD1 varchar(40),
	MOD2 varchar(40),
	MOD3 varchar(40),
	MOD4 varchar(40),
	MOD5 varchar(40),
	MOD6 varchar(40),
	MOD7 varchar(40),
	MOD8 varchar(40),
	MOD9 varchar(40),
	MOD10 varchar(40),
	VROUTING varchar(5),
	PRICE varchar(40),
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bkapi.cc_mod (
	ID bigint(19) NOT NULL auto_increment,
	MOD_ID varchar(40),
	USERNUMBER varchar(40),
	SHORTNAME varchar(400),
	LONGNAME varchar(400),
	MAXIMUM varchar(5),
	FREE varchar(5),
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
