INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH0051', '0051', 'SZ0051-WEB');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1002', '1002', 'SZ1002-CP TOWER');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1003', '1003', 'SZ1003-RGR PATTAYA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1004', '1004', 'SZ1004-RGR');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1005', '1005', 'SZ1005-WTC');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1006', '1006', 'SZ1006-MAJOR PINKLAO');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1007', '1007', 'SZ1007-SCB');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1008', '1008', 'SZ1008-FUTURE RANGSIT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1009', '1009', 'SZ1009-CENTAL BANGNA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1010', '1010', 'SZ1010-CENTRAL RAMA 3');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1011', '1011', 'SZ1011-KAD SUAN KAEW');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1012', '1012', 'SZ1012-THE MALL 8');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1014', '1014', 'SZ1014-THE MALL 6');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1015', '1015', 'SZ1015-HADYAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1016', '1016', 'SZ1016-CENTRAL LADPRAO');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1017', '1017', 'SZ1017-SIAM');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1018', '1018', 'SZ1018-KORAT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1019', '1019', 'SZ1019-SEACON SQUARE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1020', '1020', 'SZ1020-ALL SEASONS');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1021', '1021', 'SZ1021-CENTRAL AIRPORT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1022', '1022', 'SZ1022-MBK');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1023', '1023', 'SZ1023-MAJOR UDON');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1024', '1024', 'SZ1024-CENTRAL PHUKET');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1025', '1025', 'SZ1025-MAJOR EKAMAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1026', '1026', 'SZ1026-MAJOR RATCHAYOTHIN');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1027', '1027', 'SZ1027-CENTRAL RAMA 2');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1028', '1028', 'SZ1028-HUA HIN');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1029', '1029', 'SZ1029-AVENUE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1030', '1030', 'SZ1030-FASHION ISLAND');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1031', '1031', 'SZ1031-CENTRAL CHANGWATTANA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1032', '1032', 'SZ1032-CENTRAL PATTAYA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1033', '1033', 'SZ1033-THE MALL BANGKAE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1034', '1034', 'SZ1034-CENTRAL CHONBURI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1035', '1035', 'SZ1035-KHONKAEN');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1036', '1036', 'SZ1036-CENTRAL PINKLAO');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1037', '1037', 'SZ1037-THE MALL5 (THAPRA)');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1038', '1038', 'SZ1038-PARADISE PARK');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1039', '1039', 'SZ1039-PASSIONE RAYONG');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1040', '1040', 'SZ1040-CENTRAL CHIANGRAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1041', '1041', 'SZ1041-CENTRAL RAMA 9');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1042', '1042', 'SZ1042-SRIRACHA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1043', '1043', 'SZ1043-BANANA WALK PHUKET');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1044', '1044', 'SZ1044-CENTRAL UBON');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1045', '1045', 'SZ1045-CENTRAL FESTIVAL CHIANGMAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1046', '1046', 'SZ1046-CENTRAL FESTIVAL HATYAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1047', '1047', 'SZ1047-SIAM SQUARE ONE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1055', '1055', 'SZ1055-CENTRAL NAKHONSRITHAMMARAT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1048', '1048', 'SZ1048-CENTRAL WESTGATE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1049', '1049', 'SZ1049-RIVERSIDE PLAZA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1050', '1050', 'SZ1050-CENTRAL EAST VILLE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1051', '1051', 'SZ1051-ZPELL@FP RANGSIT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1052', '1052', 'SZ1052-MEGA BANGNA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1053', '1053', 'SZ1053-CENTRAL RAYONG');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1054', '1054', 'SZ1054-CENTRAL SURATTHANI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1056', '1056', 'SZ1056-BLU PORT HUA-HIN');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1057', '1057', 'SZ1057-CENTRAL SALAYA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1058', '1058', 'SZ1058-CENTRAL PHITSANULOK');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1059', '1059', 'SZ1059-AYUTTHAYA CITY PARK');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1060', '1060', 'SZ1060-V-SQUARE NAKHONSAWAN');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1061', '1061', 'SZ1061-CENTRAL KORAT');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1062', '1062', 'SZ1062-CENTRAL MAHACHAI');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1063', '1063', 'SZ1063-TERMINAL21 PATTAYA');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1064', '1064', 'SZ1064-SEACON BANGKAE');
INSERT INTO bkapi.sites(sitegroup, siteID, siteNumber, siteName) VALUES ( 'SG_SZ', 'SZTH1065', '1065', 'SZ1065-ESPLANADE RATCHADA');